project:
  type: website

website:
  title: "sua nep olong"
  navbar:
    left:
      - href: index.qmd
        text: landing...
      - href: about.qmd
        text: about me!
      - href: vis.qmd
      - href: final-project.qmd
        text: final project
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true